# version: "3.8"

x-momanim_base: &momanim_base
  working_dir: /home/mojo_user/momanim
  logging:
    driver: json-file
    options:
      max-size: 50m
  stdin_open: true
  tty: true
  shm_size: 16000000000
  ports:
    - "5910:5910"
  volumes:
    - .:/home/mojo_user/momanim/
    - ~/.ssh:/home/mojo_user/.ssh:rw
    - momanim_vscode_data_cache:/home/mojo_user/.vscode-server/data/User/globalStorage:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
  environment:
    PIXI_ENVIRONMENT_NAME: ${PIXI_ENVIRONMENT_NAME:-default}
    CONFIGURE_LIBOPENH264: ${CONFIGURE_LIBOPENH264:-false}

volumes:
  momanim_vscode_data_cache:
      external: false

services:
  momanim_build_x86_64:
    build:
      dockerfile: momanim.Dockerfile
      context: .
      args:
      - BASE_IMAGE=ubuntu:22.04
      cache_from:
      - josiahls/momanim-x86_64-cpu:${VERSION:-latest}
    image: josiahls/momanim-x86_64-cpu:${VERSION:-latest}
    profiles: ["build_cpu_x86_64"]
    platform: linux/amd64

  momanim_build_arm64:
    build:
      dockerfile: momanim.Dockerfile
      context: .
      args:
      - BASE_IMAGE=arm64v8/ubuntu:22.04
      cache_from:
      - josiahls/momanim-arm64-cpu:${VERSION:-latest}
    image: josiahls/momanim-arm64-cpu:${VERSION:-latest}
    profiles: ["build_cpu_arm64"]
    platform: linux/arm64

  momanim_build_gpu_x86_64:
    build:
      dockerfile: momanim.Dockerfile
      context: .
      args:
      - BASE_IMAGE=nvidia/cuda:12.0.0-devel-ubuntu22.04
      cache_from:
      - josiahls/momanim-x86_64-gpu:${VERSION:-latest}
    image: josiahls/momanim-x86_64-gpu:${VERSION:-latest}
    profiles: ["build_gpu_x86_64"]
    platform: linux/amd64

  #trigger
  momanim_build_gpu_arm64:
    build:
      dockerfile: momanim.Dockerfile
      context: .
      args:
      - BASE_IMAGE=nvidia/cuda:12.0.0-devel-ubuntu22.04
      cache_from:
      - josiahls/momanim-arm64-gpu:${VERSION:-latest}
    image: josiahls/momanim-arm64-gpu:${VERSION:-latest}
    profiles: ["build_gpu_arm64"]
    platform: linux/arm64

  momanim_cpu_arm64: &momanim_cpu_arm64
    <<: *momanim_base
    profiles: ["cpu_arm64"]
    restart: unless-stopped
    platform: linux/arm64
    image: josiahls/momanim-arm64-cpu:${VERSION:-latest}

  momanim_gpu_arm64: &momanim_gpu_arm64
    <<: *momanim_cpu_arm64
    profiles: ["gpu_arm64"]
    image: josiahls/momanim-arm64-gpu:${VERSION:-latest}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  momanim_cpu_x86_64: &momanim_cpu_x86_64
    <<: *momanim_base
    profiles: ["cpu_x86_64"]
    restart: unless-stopped
    platform: linux/amd64
    image: josiahls/momanim-x86_64-cpu:${VERSION:-latest}

  momanim_gpu_x86_64: &momanim_gpu_x86_64
    <<: *momanim_cpu_x86_64
    profiles: ["gpu_x86_64"]
    image: josiahls/momanim-x86_64-gpu:${VERSION:-latest}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  

